### PR TITLE
PREOPS-269: Add notes on Qserv dataset for DP0.1

### PR DESCRIPTION
**Pull request by hsinfang**

### CODE REVIEW

**Comment by hsinfang** [comment]
@fritzm  @airnandez @womullan   please review

**Review by womullan — APPROVED** [review]
Looks good - Fabio/Fritz may wish to add more on the cross check of DBs.

**Comment by airnandez** [comment]
It looks good to me. I think the level of detail is enough for this note.

**Comment by hsinfang** [comment]
Got an okay from @fritzm too. Merging next. Thank you all!

**Pull request merged**
